--Step 1 Create Table
drop table TMP_V_ITERM_POINT_2_58NR;
CREATE  TABLE
TMP_V_ITERM_POINT_2_58NR
as
select
AA.ITEMNO,AA.STUDENT_ID,AA.POINT,AA.SECTION,AA.COURSE_ID,BB.NAME_PK,BB.NAME_PK2,AA.TERM,AA.YEAR,
CC.FACULTY,AA.COURSE_ID||AA.SECTION AS COURSE_SECTION
from  SURVEY_ITEMPOINT AA 
LEFT JOIN COURSE_OPEN BB ON AA.COURSE_ID = BB.COURSE_ID AND BB.SECTION = AA.SECTION
LEFT JOIN COURSE CC ON CC.COURSE_ID = BB.COURSE_ID
WHERE BB.TERM = '2/58' AND BB.STD_TYPE = '1' AND AA."YEAR" = '2558' AND AA.TERM = '1'
AND SUBSTR(AA.STUDENT_ID,3,1) = '1' ;


--Clear DATA
DELETE  FROM TMP_V_ITERM_POINT_2_58NR
WHERE rowid not in ( SELECT MIN(rowid)
FROM TMP_V_ITERM_POINT_2_58NR
GROUP BY STUDENT_ID,
ITEMNO,
SECTION,
COURSE_ID,
NAME_PK,
NAME_PK2,
TERM) ;

-- Add FACULTY
--UPDATE 
--TMP_V_ITERM_POINT_2_58NR A1 
--SET 
--A1.FACULTY=(SELECT FACULTY FROM TEACHER A2 WHERE A2."NAME"=A1.NAME_PK )
--WHERE A1.FACULTY IS NULL
--;
UPDATE TMP_V_ITERM_POINT_2_58NR SET
FACULTY = SUBSTR(COURSE_ID,1,1) WHERE FACULTY IS NULL;

UPDATE TMP_V_ITERM_POINT_2_58NR SET FACULTY = SUBSTR(COURSE_ID,1,1) 
WHERE FACULTY = '8';


DELETE  FROM TMP_V_ITERM_POINT_2_58NR
WHERE STUDENT_ID||COURSE_ID||SECTION  IN 
(SELECT STUDENT_ID||COURSE_ID||SECTION FROM ENROLL_DATA WHERE TERM = '2/58' AND STD_TYPE='1' AND FLAG = 'W');


-- clear Data Who kpi not complete
delete   from TMP_V_ITERM_POINT_2_58NR
WHERE STUDENT_ID||SECTION||COURSE_ID
IN
(
select   STUDENT_ID||SECTION||COURSE_ID from TMP_V_ITERM_POINT_2_58NR
GROUP BY STUDENT_ID||SECTION||COURSE_ID
HAVING COUNT(*) <> 7
);


--  ลบรายวิชาฝึก
delete  from TMP_V_ITERM_POINT257_STD_TYPE2
WHERE COURSE_ID IN (SELECT COURSE_ID FROM COURSE_OPEN WHERE STD_TYPE='2' AND TERM = '2/58' AND SJGROUP='j');

