

DROP TABLE R_004_COMMENT258_GOOD_TYPE1;

CREATE TABLE R_004_COMMENT258_GOOD_TYPE1
as
select  trim(IMPRESS) as IMMPRESS,TEACHER.PRENM||TEACHER.PONAME AS T_NAME,REF_FAC.FAC_NAME_TH,SURVEY_SUGGESTION.COURSE_ID,SURVEY_SUGGESTION.SECTION,SURVEY_SUGGESTION.STUDENT_ID  
from SURVEY_SUGGESTION
LEFT JOIN COURSE_OPEN ON SURVEY_SUGGESTION.COURSE_ID = COURSE_OPEN.COURSE_ID 
AND COURSE_OPEN.SECTION =SURVEY_SUGGESTION.SECTION AND COURSE_OPEN.STD_TYPE = '2'
LEFT JOIN TEACHER ON TEACHER."NAME" = COURSE_OPEN.NAME_PK
LEFT JOIN REF_FAC ON REF_FAC.FAC_ID = TEACHER.FACULTY
WHERE COURSE_OPEN.TERM = '2/58' AND SUBSTR(STUDENT_ID,3,1) = '1'  AND COURSE_OPEN.STD_TYPE = '1'
AND COURSE_OPEN.NAME_PK IN (SELECT DISTINCT NAME_PK FROM COURSE_OPEN WHERE TERM = '2/58' AND STD_TYPE = '2')
AND SURVEY_SUGGESTION.TERM = '1'  AND SURVEY_SUGGESTION."YEAR" = '58' 
ORDER BY REF_FAC.FAC_NAME_TH,TEACHER."NAME";



delete  FROM R_004_COMMENT258_GOOD_TYPE1
WHERE rowid not in ( SELECT MIN(rowid)
FROM R_004_COMMENT258_GOOD_TYPE1
GROUP BY IMMPRESS,
T_NAME,
FAC_NAME_TH,
COURSE_ID,
STUDENT_ID) ;


-- Export 
SELECT
DISTINCT 
  "IMMPRESS" , 
	"T_NAME" , 
	"FAC_NAME_TH" , 
	"COURSE_ID" , 
	"SECTION" , 
	"STUDENT_ID"
FROM R_004_COMMENT258_GOOD_TYPE1
WHERE  "IMMPRESS" IS NOT  NULL
ORDER BY FAC_NAME_TH,T_NAME,COURSE_ID,STUDENT_ID


