DROP TABLE R_005_COMMENT_BAD258_TYPE2;

CREATE TABLE R_005_COMMENT_BAD258_TYPE2
AS
select  trim("CHANGE") as CHANG,TEACHER.PRENM||TEACHER.PONAME as T_NAME,
REF_FAC.FAC_NAME_TH,SURVEY_SUGGESTION.COURSE_ID,SURVEY_SUGGESTION.SECTION,SURVEY_SUGGESTION.STUDENT_ID  
from SURVEY_SUGGESTION
LEFT JOIN COURSE_OPEN ON SURVEY_SUGGESTION.COURSE_ID = COURSE_OPEN.COURSE_ID  AND COURSE_OPEN.STD_TYPE = '2'
AND COURSE_OPEN.SECTION =SURVEY_SUGGESTION.SECTION 
LEFT JOIN TEACHER ON TEACHER."NAME" = COURSE_OPEN.NAME_PK
LEFT JOIN REF_FAC ON REF_FAC.FAC_ID = TEACHER.FACULTY
WHERE COURSE_OPEN.TERM = '2/58' AND SUBSTR(STUDENT_ID,3,1) = '1'
AND COURSE_OPEN.NAME_PK IN (SELECT DISTINCT NAME_PK FROM COURSE_OPEN WHERE TERM = '2/58' AND STD_TYPE  = '1' )
AND SURVEY_SUGGESTION.TERM = '1'  AND SURVEY_SUGGESTION."YEAR" = '58' 
ORDER BY REF_FAC.FAC_NAME_TH,TEACHER."NAME";

SELECT 
DISTINCT
  "CHANG" , 
	"T_NAME" , 
	"FAC_NAME_TH", 
	"COURSE_ID", 
	"SECTION" , 
	"STUDENT_ID"
FROM 
R_005_COMMENT_BAD258_TYPE2
WHERE  "CHANG"  IS NOT NULL AND "CHANG"  <> '-' 
ORDER BY FAC_NAME_TH,T_NAME,COURSE_ID,STUDENT_ID